<Project>
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <AnalysisLevel>latest-recommended</AnalysisLevel>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
    <Deterministic>true</Deterministic>
    <ContinuousIntegrationBuild Condition="'$(CI)' == 'true'">true</ContinuousIntegrationBuild>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <Authors>Remone Naidoo</Authors>
    <Company>Remone Naidoo</Company>
    <Copyright>Copyright (c) 2026 Remone Naidoo</Copyright>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <IsPackable>false</IsPackable>
    <RepositoryUrl>https://github.com/remonenaidoo/swiftbets-placement</RepositoryUrl>
  </PropertyGroup>
  <PropertyGroup Condition="$(MSBuildProjectName.EndsWith('Tests'))">
    <NoWarn>$(NoWarn);CA1707;CA2201;CA1861</NoWarn>
  </PropertyGroup>
</Project>
