<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="SwiftBets.Contracts" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <ProjectReference Include="../SwiftBets.Wallet.Domain/SwiftBets.Wallet.Domain.csproj" />
  </ItemGroup>
</Project>
