<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="SwiftBets.BuildingBlocks.Persistence" />
    <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" />
    <PackageReference Include="Microsoft.Extensions.Configuration.CommandLine" />
    <PackageReference Include="SwiftBets.BuildingBlocks.Outbox" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations/*.sql" />
  </ItemGroup>
</Project>
